import { PLACE_ID, type Listing, type Shop } from "./types.js";

/**
 * Kariakoo market cluster, Dar es Salaam (~-6.8224, 39.2739).
 * Shop coordinates stay server-side until a paid order unlocks them.
 */
export const shops: Shop[] = [
  {
    id: "shop_mama_aisha",
    shopName: "Mama Aisha Kitenge",
    lat: -6.82195,
    lng: 39.27442,
    streetAddress: "Congo St, Kariakoo",
    placeId: PLACE_ID,
  },
  {
    id: "shop_swahili_threads",
    shopName: "Swahili Threads",
    lat: -6.82312,
    lng: 39.27315,
    streetAddress: "Msimbazi St, Kariakoo",
    placeId: PLACE_ID,
  },
  {
    id: "shop_kariakoo_kicks",
    shopName: "Kariakoo Kicks",
    lat: -6.82268,
    lng: 39.27501,
    streetAddress: "Uhuru St, Kariakoo",
    placeId: PLACE_ID,
  },
  {
    id: "shop_night_market_bags",
    shopName: "Night Market Bags",
    lat: -6.8214,
    lng: 39.27355,
    streetAddress: "Nyamwezi St, Kariakoo",
    placeId: PLACE_ID,
  },
  {
    id: "shop_tech_alley",
    shopName: "Tech Alley DSM",
    lat: -6.82355,
    lng: 39.2748,
    streetAddress: "Livingstone St, Kariakoo",
    placeId: PLACE_ID,
  },
  {
    id: "shop_phone_city",
    shopName: "Phone City Kariakoo",
    lat: -6.82205,
    lng: 39.27288,
    streetAddress: "Mchikichi St, Kariakoo",
    placeId: PLACE_ID,
  },
  {
    id: "shop_volt_accessories",
    shopName: "Volt Accessories",
    lat: -6.82401,
    lng: 39.2734,
    streetAddress: "Aggrey St, Kariakoo",
    placeId: PLACE_ID,
  },
  {
    id: "shop_radio_house",
    shopName: "Radio House TZ",
    lat: -6.82172,
    lng: 39.27555,
    streetAddress: "Swahili St, Kariakoo",
    placeId: PLACE_ID,
  },
];

function pic(seed: string): string {
  return `https://picsum.photos/seed/${encodeURIComponent(seed)}/640/640`;
}

const iso = (d: string) => new Date(d).toISOString();

/** 24 SKUs: fashion + electronics, mixed stock, clustered in Kariakoo. */
export const listings: Listing[] = [
  {
    id: "lst_kitenge_maxi_01",
    shopId: "shop_mama_aisha",
    title: "Kitenge maxi dress — indigo",
    priceTzs: 45000,
    category: "fashion",
    photoUrl: pic("dnols-kitenge-maxi"),
    inStock: true,
    description: "Hand-cut kitenge maxi, wrap waist. Pickup only after payment.",
    sizes: ["S", "M", "L", "XL"],
    createdAt: iso("2026-08-12T09:00:00Z"),
    trendingScore: 92,
  },
  {
    id: "lst_khanga_set_02",
    shopId: "shop_mama_aisha",
    title: "Khanga pair — coastal print",
    priceTzs: 18000,
    category: "fashion",
    photoUrl: pic("dnols-khanga-pair"),
    inStock: true,
    description: "Two-piece khanga, cotton. Popular for gifts.",
    sizes: ["one-size"],
    createdAt: iso("2026-08-18T11:20:00Z"),
    trendingScore: 88,
  },
  {
    id: "lst_dashiki_03",
    shopId: "shop_swahili_threads",
    title: "Men's dashiki shirt — gold",
    priceTzs: 32000,
    category: "fashion",
    photoUrl: pic("dnols-dashiki-gold"),
    inStock: true,
    description: "Embroidered collar dashiki. Street pickup after escrow.",
    sizes: ["M", "L", "XL", "XXL"],
    createdAt: iso("2026-08-08T14:00:00Z"),
    trendingScore: 71,
  },
  {
    id: "lst_ankara_blazer_04",
    shopId: "shop_swahili_threads",
    title: "Ankara blazer — unisex",
    priceTzs: 78000,
    category: "fashion",
    photoUrl: pic("dnols-ankara-blazer"),
    inStock: true,
    description: "Tailored ankara blazer, single button.",
    sizes: ["S", "M", "L"],
    createdAt: iso("2026-08-21T08:30:00Z"),
    trendingScore: 64,
  },
  {
    id: "lst_leso_headwrap_05",
    shopId: "shop_mama_aisha",
    title: "Leso headwrap bundle (3)",
    priceTzs: 12000,
    category: "fashion",
    photoUrl: pic("dnols-leso-wrap"),
    inStock: false,
    description: "Restock expected next market day.",
    sizes: ["one-size"],
    createdAt: iso("2026-07-30T10:00:00Z"),
    trendingScore: 40,
  },
  {
    id: "lst_sneakers_06",
    shopId: "shop_kariakoo_kicks",
    title: "Low-top sneakers — white",
    priceTzs: 55000,
    category: "fashion",
    photoUrl: pic("dnols-sneakers-white"),
    inStock: true,
    description: "Everyday low-tops. Confirm size at handover.",
    sizes: ["39", "40", "41", "42", "43", "44"],
    createdAt: iso("2026-08-22T16:00:00Z"),
    trendingScore: 85,
  },
  {
    id: "lst_slides_07",
    shopId: "shop_kariakoo_kicks",
    title: "Rubber slides — black",
    priceTzs: 15000,
    category: "fashion",
    photoUrl: pic("dnols-slides-black"),
    inStock: true,
    description: "Market-day slides, cushion sole.",
    sizes: ["40", "41", "42", "43", "44"],
    createdAt: iso("2026-08-15T12:00:00Z"),
    trendingScore: 55,
  },
  {
    id: "lst_canvas_08",
    shopId: "shop_kariakoo_kicks",
    title: "Canvas high-tops — navy",
    priceTzs: 42000,
    category: "fashion",
    photoUrl: pic("dnols-canvas-navy"),
    inStock: true,
    description: "Lace-up canvas, gum sole.",
    sizes: ["38", "39", "40", "41", "42"],
    createdAt: iso("2026-08-05T09:45:00Z"),
    trendingScore: 48,
  },
  {
    id: "lst_tote_09",
    shopId: "shop_night_market_bags",
    title: "Kitenge tote bag",
    priceTzs: 22000,
    category: "fashion",
    photoUrl: pic("dnols-kitenge-tote"),
    inStock: true,
    description: "Lined tote, inner zip pocket.",
    sizes: ["one-size"],
    createdAt: iso("2026-08-19T13:10:00Z"),
    trendingScore: 77,
  },
  {
    id: "lst_backpack_10",
    shopId: "shop_night_market_bags",
    title: "City backpack — charcoal",
    priceTzs: 38000,
    category: "fashion",
    photoUrl: pic("dnols-backpack-charcoal"),
    inStock: true,
    description: "Laptop sleeve up to 15\".",
    sizes: ["one-size"],
    createdAt: iso("2026-08-11T07:00:00Z"),
    trendingScore: 60,
  },
  {
    id: "lst_belt_11",
    shopId: "shop_swahili_threads",
    title: "Leather belt — tan",
    priceTzs: 19000,
    category: "fashion",
    photoUrl: pic("dnols-belt-tan"),
    inStock: true,
    description: "Local tannery belt, brass buckle.",
    sizes: ["85cm", "90cm", "95cm", "100cm"],
    createdAt: iso("2026-08-01T15:00:00Z"),
    trendingScore: 33,
  },
  {
    id: "lst_cap_12",
    shopId: "shop_night_market_bags",
    title: "DSM baseball cap",
    priceTzs: 14000,
    category: "fashion",
    photoUrl: pic("dnols-cap-dsm"),
    inStock: true,
    description: "Embroidered Dar es Salaam cap.",
    sizes: ["adjustable"],
    createdAt: iso("2026-08-24T10:20:00Z"),
    trendingScore: 81,
  },
  {
    id: "lst_phone_a15_13",
    shopId: "shop_phone_city",
    title: "Refurbished Android A15",
    priceTzs: 185000,
    category: "electronics",
    photoUrl: pic("dnols-phone-a15"),
    inStock: true,
    description: "90-day stall warranty. Unlock PIN at handover.",
    brand: "Generic A-series",
    createdAt: iso("2026-08-20T09:00:00Z"),
    trendingScore: 95,
  },
  {
    id: "lst_feature_14",
    shopId: "shop_phone_city",
    title: "Dual-SIM feature phone",
    priceTzs: 35000,
    category: "electronics",
    photoUrl: pic("dnols-feature-phone"),
    inStock: true,
    description: "Long battery, torch, FM radio.",
    brand: "Tecno stub",
    createdAt: iso("2026-08-14T11:00:00Z"),
    trendingScore: 70,
  },
  {
    id: "lst_earbuds_15",
    shopId: "shop_volt_accessories",
    title: "TWS earbuds — black",
    priceTzs: 28000,
    category: "electronics",
    photoUrl: pic("dnols-tws-black"),
    inStock: true,
    description: "Charging case, touch controls.",
    brand: "Volt Audio",
    createdAt: iso("2026-08-23T18:00:00Z"),
    trendingScore: 90,
  },
  {
    id: "lst_powerbank_16",
    shopId: "shop_volt_accessories",
    title: "Power bank 20 000 mAh",
    priceTzs: 42000,
    category: "electronics",
    photoUrl: pic("dnols-powerbank-20k"),
    inStock: true,
    description: "Dual USB-A + USB-C in.",
    brand: "Volt Charge",
    createdAt: iso("2026-08-10T08:00:00Z"),
    trendingScore: 74,
  },
  {
    id: "lst_charger_17",
    shopId: "shop_volt_accessories",
    title: "33W USB-C charger",
    priceTzs: 18000,
    category: "electronics",
    photoUrl: pic("dnols-charger-33w"),
    inStock: false,
    description: "Out of stock — cable still available.",
    brand: "Volt Charge",
    createdAt: iso("2026-08-03T12:30:00Z"),
    trendingScore: 22,
  },
  {
    id: "lst_cable_18",
    shopId: "shop_tech_alley",
    title: "USB-C braided cable 2m",
    priceTzs: 8000,
    category: "electronics",
    photoUrl: pic("dnols-cable-usbc"),
    inStock: true,
    description: "Reinforced ends, 60W rated.",
    brand: "Alley Cables",
    createdAt: iso("2026-08-25T07:40:00Z"),
    trendingScore: 68,
  },
  {
    id: "lst_speaker_19",
    shopId: "shop_radio_house",
    title: "Bluetooth speaker mini",
    priceTzs: 48000,
    category: "electronics",
    photoUrl: pic("dnols-bt-speaker"),
    inStock: true,
    description: "IPX4, 8h play. Demo in stall after pay.",
    brand: "Radio House",
    createdAt: iso("2026-08-17T16:15:00Z"),
    trendingScore: 79,
  },
  {
    id: "lst_radio_20",
    shopId: "shop_radio_house",
    title: "AM/FM portable radio",
    priceTzs: 26000,
    category: "electronics",
    photoUrl: pic("dnols-amfm-radio"),
    inStock: true,
    description: "USB charge + dry cells.",
    brand: "Radio House",
    createdAt: iso("2026-08-06T10:00:00Z"),
    trendingScore: 51,
  },
  {
    id: "lst_tv_21",
    shopId: "shop_tech_alley",
    title: "32\" LED TV (open box)",
    priceTzs: 320000,
    category: "electronics",
    photoUrl: pic("dnols-led-32"),
    inStock: true,
    description: "HDMI + USB. Buyer inspects at stall.",
    brand: "Alley Vision",
    createdAt: iso("2026-08-09T13:00:00Z"),
    trendingScore: 58,
  },
  {
    id: "lst_mouse_22",
    shopId: "shop_tech_alley",
    title: "Wireless mouse",
    priceTzs: 16000,
    category: "electronics",
    photoUrl: pic("dnols-mouse-wl"),
    inStock: true,
    description: "2.4 GHz dongle included.",
    brand: "Alley Peripherals",
    createdAt: iso("2026-08-16T09:20:00Z"),
    trendingScore: 44,
  },
  {
    id: "lst_keyboard_23",
    shopId: "shop_tech_alley",
    title: "Mini Bluetooth keyboard",
    priceTzs: 24000,
    category: "electronics",
    photoUrl: pic("dnols-kb-mini"),
    inStock: true,
    description: "Pairs with phones and tablets.",
    brand: "Alley Peripherals",
    createdAt: iso("2026-08-13T17:00:00Z"),
    trendingScore: 39,
  },
  {
    id: "lst_solar_24",
    shopId: "shop_volt_accessories",
    title: "Folding solar charger 21W",
    priceTzs: 65000,
    category: "electronics",
    photoUrl: pic("dnols-solar-21w"),
    inStock: true,
    description: "USB-A out, travel pouch.",
    brand: "Volt Charge",
    createdAt: iso("2026-08-26T08:00:00Z"),
    trendingScore: 83,
  },
];
